const router = require("express").Router()
const QuotationVat = require("../../controllers/order/quotationVat_controller.js")
const QuotationNoVat = require("../../controllers/order/quotationNoVat_controller.js")
const InvoiceVat = require("../../controllers/order/invoiceVat_controller.js")
const ReceiptVat = require("../../controllers/order/receiptVat_controller.js")

router.post("/quotation-vat", QuotationVat.createQuotationVat)
router.put("/quotation-vat/:id", QuotationVat.updateQuotationVat)
router.get("/quotation-vat/:id", QuotationVat.getQuotationVat)
router.get("/quotations-vat", QuotationVat.getQuotationsVat)
router.get("/quotations-vat-hide", QuotationVat.getQuotationsVatHide)
router.get("/quotations-vat-all", QuotationVat.getQuotationsVatAll)
router.get("/quotation-vat-nextno", QuotationVat.getNextQuotationVatNo)
router.delete("/quotation-vat/:id", QuotationVat.deleteQuotationVat)

router.post("/quotation-novat", QuotationNoVat.createQuotationNoVat)
router.put("/quotation-novat/:id", QuotationNoVat.updateQuotationNoVat)
router.get("/quotation-novat/:id", QuotationNoVat.getQuotationNoVat)
router.get("/quotations-novat", QuotationNoVat.getQuotationsNoVat)
router.get("/quotations-vat-hide", QuotationNoVat.getQuotationsNoVatHide)
router.get("/quotations-vat-all", QuotationNoVat.getQuotationsNoVatAll)
router.get("/quotation-novat-nextno", QuotationNoVat.getNextQuotationNoVatNo)
router.delete("/quotation-novat/:id", QuotationNoVat.deleteQuotationNoVat)

router.post("/invoice-vat", InvoiceVat.createInvoiceVat)
router.put("/invoice-vat/:id", InvoiceVat.updateInvoiceVat)
router.get("/invoice-vat/:id", InvoiceVat.getInvoiceVat)
router.get("/invoices-vat", InvoiceVat.getInvoicesVat)
router.get("/invoices-vat-hide", InvoiceVat.getInvoicesVatHide)
router.get("/invoices-vat-all", InvoiceVat.getInvoicesVatAll)
router.get("/invoice-vat-nextno", InvoiceVat.getNextInvoiceVatNo)
router.delete("/invoice-vat/:id", InvoiceVat.deleteInvoiceVat)
router.get("/invoice-vat-checkpaid/:id", InvoiceVat.checkPaidStatus)

router.post("/receipt-vat", ReceiptVat.createReceiptVat)
router.put("/receipt-vat/:id", ReceiptVat.updateReceiptVat)
router.get("/receipt-vat/:id", ReceiptVat.getReceiptVat)
router.get("/receipts-vat", ReceiptVat.getReceiptsVat)
router.get("/receipts-vat-hide", ReceiptVat.getReceiptsVatHide)
router.get("/receipts-vat-all", ReceiptVat.getReceiptsVatAll)
router.get("/receipt-vat-nextno", ReceiptVat.getNextReceiptVatNo)
router.delete("/receipt-vat/:id", ReceiptVat.deleteReceiptVat)

module.exports = router